### ISSUE TITLE
streamlit run error

### ISSUE THREAD

**Issue by zjrwtxdaydayup** [sai8151/pptgen#1]
➜  example streamlit run example.py 
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.11.1/bin/streamlit", line 5, in <module>
    from streamlit.cli import main
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/site-packages/streamlit/__init__.py", line 48, in <module>
    from streamlit.proto.RootContainer_pb2 import RootContainer
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/site-packages/streamlit/proto/RootContainer_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/root/.pyenv/versions/3.11.1/lib/python3.11/site-packages/google/protobuf/descriptor.py", line 914, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by sai8151** [comment]
> current versions of pptgen applications will work only on linux machines and don't support for windows.

**Comment by sai8151** [comment]
- How ever if you wanna downgrade the protobuf here is the thing

`
pip install protobuf==3.20.3
`

- To set the Environment Variable for windows 

`
set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
`
